version: "3"
services:
    onion:
        image: "onion:dev"
        build:
            context: .
            dockerfile: Dockerfile
        hostname: onion
        stdin_open: true
        tty: true
        working_dir: '/onion-dev'
        volumes:
            - ".:/onion-dev"
